// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3RaSl7970aGzdJXyJ6k7pXgdQmX0Ytl4',
    appId: '1:990023070558:web:7b79f6e4022201fcb615cf',
    messagingSenderId: '990023070558',
    projectId: 'lifehelper-92779',
    authDomain: 'lifehelper-92779.firebaseapp.com',
    storageBucket: 'lifehelper-92779.firebasestorage.app',
    measurementId: 'G-FFQV75P1VK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7xVvH8-PyIizX4mkBUrSVl0vG1lCVzG4',
    appId: '1:990023070558:ios:9a4e6b5b1c028e7cb615cf',
    messagingSenderId: '990023070558',
    projectId: 'lifehelper-92779',
    storageBucket: 'lifehelper-92779.firebasestorage.app',
    iosBundleId: 'com.example.lifehelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7xVvH8-PyIizX4mkBUrSVl0vG1lCVzG4',
    appId: '1:990023070558:ios:9a4e6b5b1c028e7cb615cf',
    messagingSenderId: '990023070558',
    projectId: 'lifehelper-92779',
    storageBucket: 'lifehelper-92779.firebasestorage.app',
    iosBundleId: 'com.example.lifehelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3RaSl7970aGzdJXyJ6k7pXgdQmX0Ytl4',
    appId: '1:990023070558:web:b7eb9e03004a004cb615cf',
    messagingSenderId: '990023070558',
    projectId: 'lifehelper-92779',
    authDomain: 'lifehelper-92779.firebaseapp.com',
    storageBucket: 'lifehelper-92779.firebasestorage.app',
    measurementId: 'G-2QBYTNMSN1',
  );
}
